/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(adaptive_rate_control.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ff6ac0a900ecca50fd121ce40e7c551b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/packet_protocols/adaptive_rate_control.h>
// pydoc.h is automatically generated in the build directory
#include <adaptive_rate_control_pydoc.h>

void bind_adaptive_rate_control(py::module& m)
{

    using rate_thresholds_t = ::gr::packet_protocols::rate_thresholds_t;
    using adaptive_rate_control = ::gr::packet_protocols::adaptive_rate_control;

    // Register enum before using it in default arguments
    py::enum_<::gr::packet_protocols::modulation_mode_t>(m, "modulation_mode_t")
        .value("MODE_2FSK", ::gr::packet_protocols::modulation_mode_t::MODE_2FSK)   // 0
        .value("MODE_4FSK", ::gr::packet_protocols::modulation_mode_t::MODE_4FSK)   // 1
        .value("MODE_8FSK", ::gr::packet_protocols::modulation_mode_t::MODE_8FSK)   // 2
        .value("MODE_16FSK", ::gr::packet_protocols::modulation_mode_t::MODE_16FSK) // 3
        .value("MODE_BPSK", ::gr::packet_protocols::modulation_mode_t::MODE_BPSK)   // 4
        .value("MODE_QPSK", ::gr::packet_protocols::modulation_mode_t::MODE_QPSK)   // 5
        .value("MODE_8PSK", ::gr::packet_protocols::modulation_mode_t::MODE_8PSK)   // 6
        .value("MODE_QAM16", ::gr::packet_protocols::modulation_mode_t::MODE_QAM16) // 7
        .value("MODE_QAM64", ::gr::packet_protocols::modulation_mode_t::MODE_QAM64) // 8
        .export_values();

    py::implicitly_convertible<int, ::gr::packet_protocols::modulation_mode_t>();

    py::class_<rate_thresholds_t, std::shared_ptr<rate_thresholds_t>>(
        m, "rate_thresholds_t", D(rate_thresholds_t))

        .def(py::init<>(), D(rate_thresholds_t, rate_thresholds_t, 0))
        .def(py::init<gr::packet_protocols::rate_thresholds_t const&>(),
             py::arg("arg0"),
             D(rate_thresholds_t, rate_thresholds_t, 1))

        ;


    py::class_<adaptive_rate_control,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<adaptive_rate_control>>(
        m, "adaptive_rate_control", D(adaptive_rate_control))

        .def(py::init(&adaptive_rate_control::make),
             py::arg("initial_mode") =
                 ::gr::packet_protocols::modulation_mode_t::MODE_4FSK,
             py::arg("enable_adaptation") = true,
             py::arg("hysteresis_db") = 2.,
             D(adaptive_rate_control, make))


        .def("get_modulation_mode",
             &adaptive_rate_control::get_modulation_mode,
             D(adaptive_rate_control, get_modulation_mode))


        .def("set_modulation_mode",
             &adaptive_rate_control::set_modulation_mode,
             py::arg("mode"),
             D(adaptive_rate_control, set_modulation_mode))


        .def("set_adaptation_enabled",
             &adaptive_rate_control::set_adaptation_enabled,
             py::arg("enabled"),
             D(adaptive_rate_control, set_adaptation_enabled))


        .def("update_quality",
             &adaptive_rate_control::update_quality,
             py::arg("snr_db"),
             py::arg("ber"),
             py::arg("quality_score"),
             D(adaptive_rate_control, update_quality))


        .def("recommend_mode",
             &adaptive_rate_control::recommend_mode,
             py::arg("snr_db"),
             py::arg("ber"),
             D(adaptive_rate_control, recommend_mode))


        .def("get_data_rate",
             &adaptive_rate_control::get_data_rate,
             D(adaptive_rate_control, get_data_rate))

        ;
}
