/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ax25_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(458683111a54c03247d318d8d68c4257)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/packet_protocols/ax25_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <ax25_decoder_pydoc.h>

void bind_ax25_decoder(py::module& m)
{

    using ax25_decoder = ::gr::packet_protocols::ax25_decoder;


    py::class_<ax25_decoder,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ax25_decoder>>(m, "ax25_decoder", D(ax25_decoder))

        .def(py::init(&ax25_decoder::make), D(ax25_decoder, make))


        ;
}
