/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(ax25_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(febfad6ebebb9268f1c020cf0287efbf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/packet_protocols/ax25_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <ax25_encoder_pydoc.h>

void bind_ax25_encoder(py::module& m)
{

    using ax25_encoder = ::gr::packet_protocols::ax25_encoder;


    py::class_<ax25_encoder,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<ax25_encoder>>(m, "ax25_encoder", D(ax25_encoder))

        .def(py::init(&ax25_encoder::make),
             py::arg("dest_callsign"),
             py::arg("dest_ssid"),
             py::arg("src_callsign"),
             py::arg("src_ssid"),
             py::arg("digipeaters") = "",
             py::arg("command_response") = false,
             py::arg("poll_final") = false,
             D(ax25_encoder, make))


        ;
}
