/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fx25_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2b34b5db8214d387d962ef90109199a5)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/packet_protocols/fx25_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <fx25_encoder_pydoc.h>

void bind_fx25_encoder(py::module& m)
{

    using fx25_encoder = ::gr::packet_protocols::fx25_encoder;


    py::class_<fx25_encoder,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<fx25_encoder>>(m, "fx25_encoder", D(fx25_encoder))

        .def(py::init(&fx25_encoder::make),
             py::arg("fec_type") = 2,
             py::arg("interleaver_depth") = 1,
             py::arg("add_checksum") = true,
             D(fx25_encoder, make))


        .def("set_fec_type",
             &fx25_encoder::set_fec_type,
             py::arg("fec_type"),
             D(fx25_encoder, set_fec_type))


        .def("set_interleaver_depth",
             &fx25_encoder::set_interleaver_depth,
             py::arg("depth"),
             D(fx25_encoder, set_interleaver_depth))


        .def("set_add_checksum",
             &fx25_encoder::set_add_checksum,
             py::arg("add_checksum"),
             D(fx25_encoder, set_add_checksum))

        ;
}
