/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(il2p_decoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4b68c6940faede93e9f8f31800da700a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/packet_protocols/il2p_decoder.h>
// pydoc.h is automatically generated in the build directory
#include <il2p_decoder_pydoc.h>

void bind_il2p_decoder(py::module& m)
{

    using il2p_decoder = ::gr::packet_protocols::il2p_decoder;


    py::class_<il2p_decoder,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<il2p_decoder>>(m, "il2p_decoder", D(il2p_decoder))

        .def(py::init(&il2p_decoder::make), D(il2p_decoder, make))


        ;
}
