/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(il2p_encoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(de610fa9a48afc43e7bdd28627aa8e58)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/packet_protocols/il2p_encoder.h>
// pydoc.h is automatically generated in the build directory
#include <il2p_encoder_pydoc.h>

void bind_il2p_encoder(py::module& m)
{

    using il2p_encoder = ::gr::packet_protocols::il2p_encoder;


    py::class_<il2p_encoder,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<il2p_encoder>>(m, "il2p_encoder", D(il2p_encoder))

        .def(py::init(&il2p_encoder::make),
             py::arg("dest_callsign"),
             py::arg("dest_ssid"),
             py::arg("src_callsign"),
             py::arg("src_ssid"),
             py::arg("fec_type") = 1,
             py::arg("add_checksum") = true,
             D(il2p_encoder, make))


        .def("set_fec_type",
             &il2p_encoder::set_fec_type,
             py::arg("fec_type"),
             D(il2p_encoder, set_fec_type))


        .def("set_add_checksum",
             &il2p_encoder::set_add_checksum,
             py::arg("add_checksum"),
             D(il2p_encoder, set_add_checksum))

        ;
}
