/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(kiss_tnc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3490e80f76c1541221efc9c6901e78e0)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/packet_protocols/kiss_tnc.h>
// pydoc.h is automatically generated in the build directory
#include <kiss_tnc_pydoc.h>

void bind_kiss_tnc(py::module& m)
{

    using kiss_tnc = ::gr::packet_protocols::kiss_tnc;


    py::class_<kiss_tnc,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<kiss_tnc>>(m, "kiss_tnc", D(kiss_tnc))

        .def(py::init(&kiss_tnc::make),
             py::arg("device"),
             py::arg("baud_rate") = 9600,
             py::arg("hardware_flow_control") = false,
             D(kiss_tnc, make))


        .def("set_tx_delay",
             &kiss_tnc::set_tx_delay,
             py::arg("delay"),
             D(kiss_tnc, set_tx_delay))


        .def("set_persistence",
             &kiss_tnc::set_persistence,
             py::arg("persistence"),
             D(kiss_tnc, set_persistence))


        .def("set_slot_time",
             &kiss_tnc::set_slot_time,
             py::arg("slot_time"),
             D(kiss_tnc, set_slot_time))


        .def("set_tx_tail",
             &kiss_tnc::set_tx_tail,
             py::arg("tx_tail"),
             D(kiss_tnc, set_tx_tail))


        .def("set_full_duplex",
             &kiss_tnc::set_full_duplex,
             py::arg("full_duplex"),
             D(kiss_tnc, set_full_duplex))

        ;
}
