/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(link_quality_monitor.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(232bd860f02a45f4e8c4a04f0e893f27)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/packet_protocols/link_quality_monitor.h>
// pydoc.h is automatically generated in the build directory
#include <link_quality_monitor_pydoc.h>

void bind_link_quality_monitor(py::module& m)
{

    using link_quality_monitor = ::gr::packet_protocols::link_quality_monitor;


    py::class_<link_quality_monitor,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<link_quality_monitor>>(
        m, "link_quality_monitor", D(link_quality_monitor))

        .def(py::init(&link_quality_monitor::make),
             py::arg("alpha") = 0.10000000000000001,
             py::arg("update_period") = 1000,
             D(link_quality_monitor, make))


        .def("get_snr", &link_quality_monitor::get_snr, D(link_quality_monitor, get_snr))


        .def("get_ber", &link_quality_monitor::get_ber, D(link_quality_monitor, get_ber))


        .def("get_fer", &link_quality_monitor::get_fer, D(link_quality_monitor, get_fer))


        .def("get_quality_score",
             &link_quality_monitor::get_quality_score,
             D(link_quality_monitor, get_quality_score))


        .def("update_snr",
             &link_quality_monitor::update_snr,
             py::arg("snr_db"),
             D(link_quality_monitor, update_snr))


        .def("update_ber",
             &link_quality_monitor::update_ber,
             py::arg("ber"),
             D(link_quality_monitor, update_ber))


        .def("record_frame_error",
             &link_quality_monitor::record_frame_error,
             D(link_quality_monitor, record_frame_error))


        .def("record_frame_success",
             &link_quality_monitor::record_frame_success,
             D(link_quality_monitor, record_frame_success))


        .def("reset", &link_quality_monitor::reset, D(link_quality_monitor, reset))

        ;
}
