/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(modulation_negotiation.h) */
/* BINDTOOL_HEADER_FILE_HASH(0)                                                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/packet_protocols/modulation_negotiation.h>
#include <gnuradio/packet_protocols/adaptive_rate_control.h>
// pydoc.h is automatically generated in the build directory
#include <modulation_negotiation_pydoc.h>

void bind_modulation_negotiation(py::module& m)
{

    using negotiation_msg_t = ::gr::packet_protocols::negotiation_msg_t;
    using modulation_negotiation = ::gr::packet_protocols::modulation_negotiation;
    using modulation_mode_t = ::gr::packet_protocols::modulation_mode_t;
    using adaptive_rate_control = ::gr::packet_protocols::adaptive_rate_control;


    py::class_<negotiation_msg_t, std::shared_ptr<negotiation_msg_t>>(
        m, "negotiation_msg_t", D(negotiation_msg_t))

        .def(py::init<gr::packet_protocols::negotiation_msg_t const&>(),
             py::arg("arg0"),
             D(negotiation_msg_t, negotiation_msg_t, 0))
        .def(py::init<>(), D(negotiation_msg_t, negotiation_msg_t, 1))

        ;


    py::class_<modulation_negotiation,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<modulation_negotiation>>(
        m, "modulation_negotiation", D(modulation_negotiation))

        .def(py::init([](const std::string& station_id,
                         const std::vector<modulation_mode_t>& supported_modes,
                         int negotiation_timeout_ms) {
                 return modulation_negotiation::make(station_id, supported_modes, negotiation_timeout_ms);
             }),
             py::arg("station_id"),
             py::arg("supported_modes"),
             py::arg("negotiation_timeout_ms"),
             D(modulation_negotiation, make))
        .def(py::init([](const std::string& station_id,
                         const std::vector<modulation_mode_t>& supported_modes) {
                 return modulation_negotiation::make(station_id, supported_modes, 5000);
             }),
             py::arg("station_id"),
             py::arg("supported_modes"),
             D(modulation_negotiation, make))


        .def("initiate_negotiation",
             &modulation_negotiation::initiate_negotiation,
             py::arg("remote_station_id"),
             py::arg("proposed_mode"),
             D(modulation_negotiation, initiate_negotiation))


        .def("get_negotiated_mode",
             &modulation_negotiation::get_negotiated_mode,
             D(modulation_negotiation, get_negotiated_mode))


        .def("is_negotiating",
             &modulation_negotiation::is_negotiating,
             D(modulation_negotiation, is_negotiating))


        .def("send_quality_feedback",
             &modulation_negotiation::send_quality_feedback,
             py::arg("remote_station_id"),
             py::arg("snr_db"),
             py::arg("ber"),
             py::arg("quality_score"),
             D(modulation_negotiation, send_quality_feedback))


        .def("get_supported_modes",
             &modulation_negotiation::get_supported_modes,
             D(modulation_negotiation, get_supported_modes))

        .def("set_kiss_frame_sender",
             &modulation_negotiation::set_kiss_frame_sender,
             py::arg("callback"),
             "Set callback function for sending KISS frames")

        .def("set_auto_negotiation_enabled",
             [](modulation_negotiation& self, bool enabled, 
                std::shared_ptr<adaptive_rate_control> rate_control) {
                 adaptive_rate_control* ptr = rate_control ? rate_control.get() : nullptr;
                 self.set_auto_negotiation_enabled(enabled, ptr);
             },
             py::arg("enabled"),
             py::arg("rate_control") = nullptr,
             "Enable automatic negotiation when mode changes")

        ;

    py::enum_<::gr::packet_protocols::negotiation_msg_type_t>(m, "negotiation_msg_type_t")
        .value("NEG_REQ", ::gr::packet_protocols::negotiation_msg_type_t::NEG_REQ)   // 0
        .value("NEG_RESP", ::gr::packet_protocols::negotiation_msg_type_t::NEG_RESP) // 1
        .value("NEG_ACK", ::gr::packet_protocols::negotiation_msg_type_t::NEG_ACK)   // 2
        .value("NEG_REJECT",
               ::gr::packet_protocols::negotiation_msg_type_t::NEG_REJECT) // 3
        .value("MODE_CHANGE",
               ::gr::packet_protocols::negotiation_msg_type_t::MODE_CHANGE) // 4
        .value("QUALITY_FEEDBACK",
               ::gr::packet_protocols::negotiation_msg_type_t::QUALITY_FEEDBACK) // 5
        .export_values();

    py::implicitly_convertible<int, ::gr::packet_protocols::negotiation_msg_type_t>();
}
